apps/adopcion/urls.py
from django.conf.urls import url
from apps.adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete,  \
	SolicitudShow



urlpatterns = [
	url(r'^index$', index_adopcion),
	url(r'^solicitud/listar$',SolicitudList.as_view(), name="solicitud_listar" ),
	url(r'^solicitud/nueva$', SolicitudCreate.as_view(), name="solicitud_crear" ),
	url(r'^solicitud/editar/(?P<pk>\d+)$', SolicitudUpdate.as_view() , name="solicitud_editar" ),
	url(r'^solicitud/eliminar/(?P<pk>\d+)$', SolicitudDelete.as_view() , name="solicitud_eliminar" ),
	url(r'^solicitud/mostrar/(?P<pk>\d+)$', SolicitudShow.as_view() , name="solicitud_mostrar" ),
]

apps/mascota/urls.py
from django.conf.urls import url, include

from django.contrib.auth.decorators import login_required

from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
	MascotaList, MascotaCreate ,MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    url(r'^listar', login_required(MascotaList.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),
    
    
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login,logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^',login, {'template_name':'index.html'}, name="login"),
    url(r'^logout/', logout_then_login, name='logout'),

]

apps/adopcion/models.py
from django.db import models

# Create your models here.


class Persona(models.Model):
	nombre = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=70)
	edad = models.IntegerField()
	telefono = models.CharField(max_length=12)
	email = models.EmailField()
	domicilio = models.TextField()

	def __str__(self):
		return '{}{}'.format(self.nombre, self.apellidos)

	

class Solicitud(models.Model):
	persona = models.ForeignKey(Persona, null=True, blank=True)
	numero_mascotas = models.IntegerField()
	razones = models.TextField()

apps/adopcion/forms.py
from django import forms
from apps.adopcion.models import Persona, Solicitud



class PersonaForm(forms.ModelForm):

	class Meta:
		model = Persona
		fields = [
			'nombre',
			'apellidos',
			'edad',
			'telefono',
			'email',
			'domicilio',
		]
		labels = {
			'nombre': 'Nombre',
			'apellidos': 'Apellidos',
			'edad': 'Edad',
			'telefono': 'Teléfono',
			'email': 'Correo electrónico',
			'domicilio': 'Domicilio',
		}
		widgets = {
			'nombre':forms.TextInput(attrs={'class':'form-control'}),
			'apellidos':forms.TextInput(attrs={'class':'form-control'}),
			'edad':forms.TextInput(attrs={'class':'form-control'}),
			'telefono':forms.TextInput(attrs={'class':'form-control'}),
			'email':forms.TextInput(attrs={'class':'form-control'}),
			'domicilio':forms.Textarea(attrs={'class':'form-control'}),
		}


class SolicitudForm(forms.ModelForm):

	class Meta:
		model = Solicitud
		fields = [
			'numero_mascotas',
			'razones',	
		]
		labels = {
			'numero_mascotas': 'Numero de mascotas',
			'razones': 'Razones para adoptar',
			
		}
		widgets = {
			'numero_mascotas':forms.TextInput(attrs={'class':'form-control'}),
			'razones':forms.Textarea(attrs={'class':'form-control'}),
}

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.

from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from apps.adopcion.models import Persona, Solicitud
from apps.adopcion.forms import PersonaForm, SolicitudForm

from django.core.urlresolvers import reverse_lazy

def index_adopcion(request):
	return HttpResponse("pagina principal de la app adopcion")



class SolicitudList(ListView):
	model = Solicitud
	template_name = 'adopcion/solicitud_list.html'
	


class SolicitudCreate(CreateView):
	model = Solicitud
	template_name = 'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class = PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')

	def get_context_data(self, **kwargs):
		context = super(SolicitudCreate, self).get_context_data(**kwargs)
		if 'form' not in context:
			context['form'] = self.form_class(self.request.GET)
		if 'form2' not in context:
			context['form2'] = self.second_form_class(self.request.GET)
		return context

	def post(self, request, **kwargs):
		self.object = self.get_object
		form = self.form_class(request.POST)
		form2 = self.second_form_class(request.POST)
		if form.is_valid() and form2.is_valid():
			solicitud = form.save(commit=False)
			solicitud.persona = form2.save()
			solicitud.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return self.render_to_response(self.get_context_data(self=form, form2=form2))



class SolicitudUpdate(UpdateView):
	model =  Solicitud
	second_model = Persona
	template_name =  'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class =  PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')


	def get_context_data(self,   **kwargs):
		context = super(SolicitudUpdate , self).get_context_data(**kwargs)
		pk = self.kwargs.get('pk',0)
		solicitud = self.model.objects.get(id=pk)
		persona = self.second_model.objects.get(id=solicitud.persona_id)
		if 'form' not in context:
			context['form'] = self.form_class()
		if 'form2' not in context:
			context['form2'] = self.second_form_class(instance=persona)
			context['id']=pk
		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		id_solicitud = kwargs['pk']
		solicitud = self.model.objects.get(id=id_solicitud)
		persona = self.second_model.objects.get(id=solicitud.persona_id)
		form = self.form_class(request.POST, instance=solicitud)
		form2 = self.second_form_class(request.POST, instance=persona)
		if form.is_valid() and form2.is_valid():
			form.save()
			form2.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return HttpResponseRedirect(self.get_success_url())



class SolicitudDelete(DeleteView):
	model = Solicitud
	template_name = 'adopcion/solicitud_delete.html'
	success_url = reverse_lazy('adopcion:solicitud_listar')


class SolicitudShow(DetailView):
	model =  Solicitud
	template_name = 'adopcion/solicitud_show.html'

	

templates/adopcion/solicitud_delete.html
{% extends 'base/base.html' %}

{%block content%}
	<form method="post">
		{%csrf_token%}
		<h3>Desea eliminar la solicitud {{ object.persona.nombre}} {{ object.persona.apellido}}</h3>

		<button type="submit" class="btn btn-danger">Si eliminar</button>
		<a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>

	</form>

{%endblock%}

templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.nombre.name}}">{{form2.nombre.label}}</label>
				{{form2.nombre}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.nombre.apellidos}}">{{form2.apellidos.label}}</label>
				{{form2.apellidos}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.edad.name}}">{{form2.edad.label}}</label>
				{{form2.edad}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.email.name}}">{{form2.email.label}}</label>
				{{form2.email}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.telefono.name}}">{{form2.telefono.label}}</label>
				{{form2.telefono}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.domiclio.name}}">{{form2.domicilio.label}}</label>
				{{form2.domicilio}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.numero_mascotas.name}}">{{form.numero_mascotas.label}}</label>
				{{form.numero_mascotas}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.razones.name}}">{{form.razones.label}}</label>
				{{form.razones}}
			</div>
		</div>
	</div>
	<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary" type="submit">Guardar</button>
			</div>
		</div>
</form>
{% endblock %}

templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>No. Solicitud</td>
			<td>Adoptante</td>
			<td>No. Mascotas</td>
			<td>Razones</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for solicitud in object_list %}
		<tr>
			<td>{{ solicitud.id }}</td>
			<td>{{ solicitud.persona.nombre }} {{solicitud.persona.apellidos}}</td>
			<td>{{ solicitud.numero_mascotas }}</td>
			<td>{{ solicitud.razones }}</td>
			
			<td>
				<a class="btn btn-primary" href="{% url 'adopcion:solicitud_mostrar' solicitud.id %}">Ver</a>
				<a class="btn btn-primary" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
				<a class="btn btn-danger" href="{%url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de solicitudes</h1>
		{% endif %}
	</tbody>
</table> 

{% endblock%}

templates/adopcion/solicitud_show.html
{% extends 'base/base.html' %}


{% block content %}

<p>Numero de solicitud:<strong>{{ solicitud.id }}</p></strong>
<p>Sdoptante:<strong>{{ solicitud.persona.nombre }} {{solicitud.persona.apellidos}}</p></strong>
<p>Numero de Mascotas:<strong>{{ solicitud.numero_mascotas }}</p></strong>
<p>Razones:<strong>{{ solicitud.razones }}</p></strong>

<a class="btn btn-primary" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
<a class="btn btn-danger" href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>
			

{% endblock %}